### ISSUE TITLE
Always "green" master

### ISSUE THREAD

**Issue by 3Hren** [sonm-io/core#1]
It's not-so-commonly-bad idea to keep master branch in always "green" state. For example it's extremely useful for new users to start working on in just `git clone & make` pattern.

I see travis, so let it be the tracking issue until it is repaired.

If accepted, it may also be useful to configure repo settings by protecting master branch from merging without CI passing and/or review.

**Comment by Sokel** [comment]
Thanks.
We work for them now, see [develop branch](https://github.com/sonm-io/core/tree/develop)

**Comment by Sokel** [comment]
master branch is protected now.
develop branch will be protected soon.
Build history you will see [here](https://travis-ci.org/sonm-io/core/branches).
Thanks for your improvements.

**Comment by 3Hren** [comment]
Great! Thanks!
чт, 27 июля 2017 г. в 18:17, Anton Shchukin <notifications@github.com>:
