### ISSUE TITLE
Cannot get worker status

### ISSUE THREAD

**Issue by usermax83** [sonm-io/core#1171]
**Components version**
Which components are affected and their versions. The version can be obtained using the following:
```bash
$ <cmd> --version
```
4.3.48(1)-release (x86_64-pc-linux-gnu)

```bash
$ sonmworker --version
worker v0.4.3-76cf6c3a (linux/amd64/go1.10.2)
```

**Describe the bug**
After doing the installation steps for a supplier seems that no worker has been added in https://sonm-io.github.io/gui/#/market/workers waiting for confirmation.

Running "sonmcli worker status" returns this error:
[ERR] Cannot get worker status: rpc error: code = Unknown desc = cannot connect to worker: failed to connect to [relay.livenet.sonm.com:12240]: dial tcp 0.0.0.0:12240: connect: connection refused, failed to perform handshake into relay: no peer found

"sudo docker ps" returns no containers

 - OS - ubuntu 16.04 TLS

**Comment by 3Hren** [comment]
Hi!

Seems like your worker has failed to publish itself to our rendezvous server. This can be, for example, when it has no master confirmation.

Please show the output of:
```bash
sonmcli worker current
sonmcli master list
```

**Comment by usermax83** [comment]
I saw in the log that the worker failed to start because of missing GPU driver.
