### ISSUE TITLE
task restoration on worker service restart

### ISSUE THREAD

**Issue by avsigaev** [sonm-io/core#1423]
I have 2 tasks running within 1 deal.
When I restart worker, it loose 1 task

developer@host-worker-0-3:~$ sonmcli worker status
Uptime:             4m25s
Version:            v0.4.10-f7a8268 linux/amd64/go1.10
Eth address:        0xEEBc720552B116A8C3bAF4AaeCf762A45254814a
Task count:         1
DWH status:         :15010
Rendezvous status:  79.137.70.2:14099

developer@host-worker-0-3:~$ sonmcli worker tasks
ID: 27450192-46d6-4acf-a3d2-3bbc19d535ea
  Image:  docker.io/sonm/eth-claymore:latest
  Status: RUNNING
  Uptime: 38m35.934967291s

developer@host-worker-0-3:~$ docker ps --format  'table {{.Names}}\t {{.Label "sonm.dealid"}} \t{{.Image}} \t {{.RunningFor}}'
NAMES                dealid             IMAGE                        CREATED
thirsty_shannon      6260               httpd                        33 minutes ago
gifted_stallman      6260               sonm/eth-claymore:latest     38 minutes ago

**Comment by sshaman1101** [comment]
Is this still relevant?

**Comment by sshaman1101** [comment]
As nobody replied, I'm closing this for now.
