### ISSUE TITLE
"sonmcli profile status" displays an incorrect number of current orders

### ISSUE THREAD

**Issue by DPolygalov** [sonm-io/core#1437]
➜ target git:(master) ✗ sonmcli_darwin_x86_64 order list
No orders found
➜ target git:(master) ✗ sonmcli_darwin_x86_64 profile status
User ID: 0x517648Ec2E592969Ec344642034F079c52AfD025 (REGISTERED)
Active orders: 9 Bids, 1 Asks
Certificates:
10) KYC2: true

**Comment by oopcode** [comment]
i cannot reproduce that, actually

**Comment by DPolygalov** [comment]
Failed to repeat.
