### ISSUE TITLE
Deal open transaction failed, however, deal is opened

### ISSUE THREAD

**Issue by DPolygalov** [sonm-io/core#1467]
DEV-878

$ sonmcli_linux_x86_64 order create bid.yaml --config ./cli_client.yaml 
ID = 521
$ sonmcli_linux_x86_64 deal open 520 521 --config ./cli_client.yaml 
[ERR] cannot open deal: rpc error: code = Unknown desc = could not open deal in blockchain: transaction failed
$ sonmcli_linux_x86_64 deal list  --config ./cli_client.yaml 
ID:           106 (Forward deal)
ASK ID:       520
BID ID:       521
Status:       DEAL_ACCEPTED
Price:        0 USD (0 USD/sec)
Duration:     10h0m0s
Total payout: 0 SNM
Consumer ID:  0x3CE82D2F358bf6A715FE143F11b470F0F92daf22
Supplier ID:  0x950FF0A8D20AbC2ca88EF6d0de9b1e27C378BCe1
Start at:     2018-07-30T10:18:14Z
Last bill:    2018-07-30T10:18:14Z

**Comment by sshaman1101** [comment]
AFAIR It was related to the test-net environment as of several months ago, and nobody spotted this behavior in the live-net.
Hope we'll never be forced to reopen this.
