### ISSUE TITLE
SONM Logo Not Appearing on README.md

### ISSUE THREAD

**Issue by AlexLeung** [sonm-io/core#148]
When I try to follow the link to the logo I get a response which reads `Error Fetching Resource`.
Coming from North-American IP.

**Comment by duckybsd** [comment]
Same here Australia, this link is this:

https://camo.githubusercontent.com/98a8e087cd0bb092a1c6ae5d9b2b0342b678d4be/68747470733a2f2f77696b692e736f6e6d2e696f2f6c69622f6578652f66657463682e7068703f773d33303026746f6b3d323434386566266d656469613d736f6e6d2d6c6f676f5f6e6f2d746578742e706e67

**Comment by AlexLeung** [comment]
Looks like it has been fixed! Nice!
