### ISSUE TITLE
Wrong profitability estimation (lowest possible benchmarks estimated as $1.5/day)

### ISSUE THREAD

**Issue by iolebedev** [sonm-io/core#1542]
I am testing new profitability calculator form.

I try to set all benchmark values to their lowest (preferably zero) values and expect to see profitability = zero.

<img width="1026" alt="image" src="https://user-images.githubusercontent.com/30413234/45966385-a2ae5800-c033-11e8-9380-34c32bf2ff4b.png">

I expect to see estimated income = zero (or reasonably VERY low value).
Seems like the estimation is not really correct, the value I see is unreasonably high.

**Steps to reproduce and details**

**Here is what HTML page sends (XHR):**

POST /OrderPredictorServer/Predict/ HTTP/1.1
Host: node.livenet.sonm.com
<...blah blah more headers...>
Referer: http://192.168.1.167:3000/
content-type: text/plain;charset=UTF-8
origin: http://192.168.1.167:3000
Content-Length: 274
Connection: keep-alive

{"network":{"overlay":false,"outbound":true,"incoming":true},"benchmarks":{"ram-size":0,"storage-size":0,"net-download":0,"net-upload":0,"gpu-count":0,"gpu-mem":0,"gpu-eth-hashrate":0,"gpu-cash-hashrate":0,"cpu-sysbench-multi":2000,"cpu-sysbench-single":1100,"cpu-cores":2}}

**Response:**

{"perSecond":"13695351936703"}

**Which renders as:**

Your estimated income
1 hour: $ 0.0493
24 hours: $ 1.1832
30 days: $ 35.4983

**Comment by 3Hren** [comment]
Fixed in https://github.com/sonm-io/core/pull/1571.
