### ISSUE TITLE
SIGSEGV during call sonmcli with --insecure flag

### ISSUE THREAD

**Issue by avsigaev** [sonm-io/core#1581]
Insecure connections are allowed in node config.

sonmcli token balance --insecure

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x436f96e]

**Comment by sshaman1101** [comment]
I can't reproduce the problem on current master. Can you please provide more details about this issue?
