### ISSUE TITLE
The partner instant exchange SimpleSwap.io

### ISSUE THREAD

**Issue by SimpleSwap** [sonm-io/core#1806]
Hi,

I am Nicolas, the manager at SimpleSwap.io, an instant cryptocurrency exchange.

We present a simple and easy-to-use platform that works without registration and limits and allows users to make swaps in just two clicks.

We successfully support SNM on our service for a long time and we have been exchanging SNM for more than 200 coins to our customers. I tried to find contact with your team but without results.

I'm sorry that I invaded here, but maybe you can tell me where I can turn. I would like to make contact so we can have an interaction.

**Comment by DPolygalov** [comment]
Hi Nicolas, give your email or telegram please.

**Comment by SimpleSwap** [comment]
Please contact me via email: hello@simpleswap.io
Much thanks!

**Comment by DPolygalov** [comment]
Contacted by e-mail
