### ISSUE TITLE
Add enviroments to develop and integrate blockchain into core

### ISSUE THREAD

**Issue by Sokel** [sonm-io/core#3]
Move smart contracts into `core` repository:
- [x] initied new truffle enviroment 
- [x] renew version of open-zeppelin, review and test them
- [x] move ours smart contract from [The-Factory](https://github.com/sonm-io/The-Factory)
- [x] up to date new version of solidity to our contract
- [x] review `SonmDummyToken` contract and tests
- [x] review `Factory` contract and tests
- [x] review interfaces interfaces in `Declaration`
- [x] review `HubWallet` contract and tests
- [x] review `MinerWallet` contract and tests
- [x] review `Whitelist` contract ant tests
- [x] add any develop scripts for lazzy dev

For blockchain develpment:
- [x] make abigen and go-codegeneration script and tasks
- [x] wrote wrappers/api for usage in repo

@jorpic Need to research tests implementation in golang and update this article with your decides.

**Comment by jorpic** [comment]
А кто это будет делать?

**Comment by Sokel** [comment]
@jorpic best way - do it yourself.
see [some feature branch](https://github.com/sonm-io/core/tree/feature/invoke_blockchain_into_core) for these.
ps: english please.
