### ISSUE TITLE
question-how to contribute to this project

### ISSUE THREAD

**Issue by dghadi1** [sonm-io/core#368]
I'm very interested in this project and I'm looking to spend significant amount of my time to learn and contribute. Please suggest where and how I can start.

I already joined the testnet by following the installation instructions.

I'm a DevOps engineer with expertise on docker, kubernetes, swarm and mesos.

**Comment by goktugyil** [comment]
+1 here. Also another question to ask is, are you guys looking for outside help or prefer doing everything in-team?

**Comment by dzendmitry** [comment]
+1 experience in golang and docker

**Comment by 3Hren** [comment]
Hi all!

Currently we're developing according to our roadmap, so if you're interested in developing - you're welcome.

However, bug fixes and minor things like docs or spelling issues are easier places to start.

By the way, we have a [$ rewarded challenge](https://sonm.com/challenge/) - here's the right place go start.
