### ISSUE TITLE
Miner sometimes hangs during discovery start up

### ISSUE THREAD

**Issue by 3Hren** [sonm-io/core#45]
Here: https://github.com/sonm-io/core/blob/master/insonmnia/miner/server.go#L388.

**Comment by Sokel** [comment]
@3Hren may you set log level for go-ethereum to 10, [this](https://github.com/sonm-io/core/blob/master/common/const.go#L10), and give it me?

**Comment by 3Hren** [comment]
It printed nothing:

```
⇒  ./sonmminer
2017-08-07T13:24:34.439+0300	INFO	miner/overseer.go:141	subscribe to Docker events	{"since": "1502101474"}
INFO [08-07|13:24:34] Starting P2P networking
```

I've checked the Hub with this logging level and it emitted tons of logs.

**Comment by 3Hren** [comment]
@Sokel is this resolved after eliminating whisper?

**Comment by Sokel** [comment]
@3Hren yeap
