### ISSUE TITLE
Authenticate Hub/Miner via WhiteList smart contract

### ISSUE THREAD

**Issue by jorpic** [sonm-io/core#49]
Hub and miner should be able to:
 - authenticate each other using ETH-addresses and ECDSA;
 - get some info (e.g. deposit, status) about each other from the WhiteList smart contract.

Features:

 - [ ] blockchain-related configuration section in config file
  - Eth JSON-RPC provider to use
  - Eth network id
  - Eth credentials (private key / path to json wallet / etc)
 - [ ] allow to run hub/miner in *trust all* mode, i.e. without blockchain-related configuration
 - [ ] basic challenge-response protocol to authenticate each other
 - [ ] get peer info from `WhiteList` contract
   - there is no use for this info currently, so it is enough to drop it to log

**Comment by jorpic** [comment]
Hey guys, please check this authentication protocol proposal (it is based on the protocol by Denning&Sacco which is a modification of the classic Needham&Schroeder).

Goals of the protocol:

  - exchange identities (ETH-addresses)
  - prove that contragents are aware whom they are communicating with
  - generate private session id tat can be used to establish secure communication channel
  - some messages can be used as a proof of communication in ETH smart-contract

Protocol steps:

  - **A sends** `AuthInitRequest`
    - `timestamp`
    - nonce hash: `nonceHash = SHA3(nonceA | timestamp)`
    - message signature
  - **B checks**
    - signature is valid, get `pkA` (A's public key), `addrA` (A's ETH address)
    - `timestamp` is valid (within 30 minutes interval)
  - **B sends** `AuthInitResponse` encrypted with `pkA`
    - `addrA`
    - `nonceHash`
    - `nonceB`
    - message signature
  - **A checks**
    - signature is valid, get `pkB` (B's public key), `addrB` (B's ETH address)
    - `nonceHash` is valid
  - **A sends** `AuthCommitRequest` encrypted with `pkB`
   - `addrB`
    - `nonceA`, `nonceB`
    - message signature
  - **B checks** `
    - signature is valid
    - `nonceHash = SHA3(nonceA | timestamp)`
  - **B sends** `AuthCommitResponse` encrypted with `pkA`
   - `addrA`
    - `nonceA`, `nonceB`
    - message signature

Communication is complete, `SHA3(nonceA | nonceB)` can be used as private session id.

Notes:
  - each message contains `message type` field
  - secp256k1 is used to sign messages
  - ECIES is used to encrypt messages

**Comment by Sokel** [comment]
Great proposal, thanks. 
We must implemented this auth issue above whisper protocal.
Whisper have all prerequisites for it.

PS: one r&d version of discovery alg alredy have it, but we hold over this, because identity wasn't complete at time.

**Comment by jorpic** [comment]
Ok. It's much easier to do this over whisper as it already provides signatures and encryption.

But there are some issues:

  - Session id must be used to authenitcate communication over gRPC.
  - Currently, whisper is not used when Miner knows Hub's IP. Do we need to start gRPC communication only after authentication over whisper is done? This may be quite slow due to unpredicted whisper latency.

**Comment by Sokel** [comment]
1. it will be [there](https://github.com/sonm-io/core/blob/master/insonmnia/hub/miner_ctx.go#L69), before 

2. - p2p server (shh-protocol include) will be always on in next release.
    - yes, it you're right.  We need to have some speeches with @noxiouz about [grpc-auth](https://grpc.io/docs/guides/auth.html)

**Comment by jorpic** [comment]
What is the point of having two authentication methods simultaneously (one over whisper and another one over grpc)?

Maybe it is better to have just one over gRPC?
Anyway, gRPC communication should be authenticated and secured as it is used to transfer metrics and tasks.

What is the point of authentication over whisper?

**Comment by Sokel** [comment]
I invited @noxiouz  to this topic.

**Comment by noxiouz** [comment]
gRPC has extendable auth mechanism, I prefer to use it. Also, we have to use it anyway to auth hub/miner communication.

**Comment by noxiouz** [comment]
In my point of view whisper is just a way to know Hub's IP. This info must be signed. Aftet that, whrn the connection from a miner to a hub is being established, both sides should have a mechanism to auth each other (pub/private keypair for example). The only question for me is how to get pubkeys.

**Comment by jorpic** [comment]
I just added sharing Hub's public key over whisper (IP is signed with this key also): https://github.com/sonm-io/core/pull/70

Next I'll try to investigate how to use ECDSA keys to authenticate over gRPC.
