### ISSUE TITLE
Failed to execute "sonmcli get"

### ISSUE THREAD

**Issue by greatsxm** [sonm-io/core#494]
hello, dear guys.
       I have started sonm on my private blockchain which has been deployed sonm contract. I have tried to get some snmt for an account with command "sonmcli get", but it seemed failed.
       Although,   "sonmcli get" command did not output error information, sonmnode output error information like this. It means the account has not enough balance.

2018-02-22T07:59:40.698+0800	INFO	node/market.go:400	lack of balance or allowance for order, skip	{"orderID": "d65ec42b-383a-4acc-9ee4-67045cdb44fb", "price": "3600000000000000000000", "balance": "0", "allowance": "1000000000000000013287555072"}

Can anyone help me?

**Comment by greatsxm** [comment]
I enlargered the gasLimit and solved this problem.  But another error information (from hub) came as follow:


2018-02-24T17:31:16.855+0800	ERROR	zap/server_interceptors.go:39	finished unary call	{"grpc.start_time": "2018-02-24T17:31:16+08:00", "system": "grpc", "span.kind": "server", "grpc.service": "sonm.Hub", "grpc.method": "ProposeDeal", "peer.wallet": "0x53F4f1208013168F7fbF8E2A1E70e2aF7655B88D", "span.trace_id": "59f932732a179c1f", "span.span_id": "28b0c0c458be5711", "error": "order already exists", "grpc.code": "Unknown", "grpc.time_ms": 4.234000205993652}
github.com/sonm-io/core/vendor/go.uber.org/zap.Stack
	/home/songxm/devel/ethereum/sonm/sonm-io/gopath_eth/src/github.com/sonm-io/core/vendor/go.uber.org/zap/field.go:209
github.com/sonm-io/core/vendor/go.uber.org/zap.(*Logger).check
	/home/songxm/devel/ethereum/sonm/sonm-io/gopath_eth/src/github.com/sonm-io/core/vendor/go.uber.org/zap/logger.go:273
github.com/sonm-io/core/vendor/go.uber.org/zap.(*Logger).Check
	/home/songxm/devel/ethereum/sonm/sonm-io/gopath_eth/src/github.com/sonm-io/core/vendor/go.uber.org/zap/logger.go:146
github.com/sonm-io/core/vendor/github.com/grpc-ecosystem/go-grpc-middleware/logging/zap.UnaryServerInterceptor.func1
	/home/songxm/devel/ethereum/sonm/sonm-io/gopath_eth/src/github.com/sonm-io/core/vendor/github.com/grpc-ecosystem/go-grpc-middleware/logging/zap/server_interceptors.go:39
github.com/sonm-io/core/vendor/github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1
	/home/songxm/devel/ethereum/sonm/sonm-io/gopath_eth/src/github.com/sonm-io/core/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:37
github.com/sonm-io/core/proto._Hub_ProposeDeal_Handler
	/home/songxm/devel/ethereum/sonm/sonm-io/gopath_eth/src/github.com/sonm-io/core/proto/hub.pb.go:1300
github.com/sonm-io/core/vendor/google.golang.org/grpc.(*Server).processUnaryRPC
	/home/songxm/devel/ethereum/sonm/sonm-io/gopath_eth/src/github.com/sonm-io/core/vendor/google.golang.org/grpc/server.go:920
github.com/sonm-io/core/vendor/google.golang.org/grpc.(*Server).handleStream
	/home/songxm/devel/ethereum/sonm/sonm-io/gopath_eth/src/github.com/sonm-io/core/vendor/google.golang.org/grpc/server.go:1142
github.com/sonm-io/core/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1
	/home/songxm/devel/ethereum/sonm/sonm-io/gopath_eth/src/github.com/sonm-io/core/vendor/google.golang.org/grpc/server.go:637

**Comment by 3Hren** [comment]
@Sokel, is `sonmcli get` handle still relevant?
