### ISSUE TITLE
Failed to start task

### ISSUE THREAD

**Issue by greatsxm** [sonm-io/core#497]
Hi,all.
     I had a try on sonm of version 0.3.3. I wanted to start a task of "httpd" as detailed in the file task.yaml.
     Error information is showed as follow:

[ERR] Cannot start task: rpc error: code = Internal desc = failed to start rpc error: code = Internal desc = failed to Spool Error response from daemon: Get https://registry-1.docker.io/v2/library/httpd/manifests/latest: Get https://auth.docker.io/token?scope=repository%3Alibrary%2Fhttpd%3Apull&service=registry.docker.io: net/http: TLS handshake timeout

     Or as:

[ERR] Cannot start task: rpc error: code = DeadlineExceeded desc = context deadline exceeded

**Comment by 3Hren** [comment]
Hi!

Seems like you're reached timeout while spooling your application from Docker Registry. Try to increase the deadline using `--timeout` flag.

**Comment by avsigaev** [comment]
HI!

You may ask these kind of questions in our Telegram chat https://t.me/SONMbetatest
More chances to get quicker answer.
