### ISSUE TITLE
Metrics collection from miner (CPU, Memory)

### ISSUE THREAD

**Issue by iolebedev** [sonm-io/core#5]
Collect metrics collection from miner (CPU, Memory), report to hub.
- [x] Metrics from Docker (used CPU, Memory).
- [ ] Metrics from OS (total CPU, Memory).
- [x] Communication through gRPC.
- [x] Hub requests report.
- [x] Miner provide report.

**Comment by 3Hren** [comment]
Seems reasonable to transmit host configuration, including total CPU, memory etc, in the handshake frame (which is currently unimplemented).
