### ISSUE TITLE
Is there a way to tell if the market is down?

### ISSUE THREAD

**Issue by dannysemi** [sonm-io/core#529]
I'm getting connection refused errors when I try to run the default configs from the getting started guide.

**Comment by 3Hren** [comment]
What do you mean by "connection refused errors"? Where? How to reproduce?

**Comment by dannysemi** [comment]
1. Clean ubuntu 16.04 install.
2. Edit hub.yaml according to getting started guide.
3. Execute sonmhub script.
4. Prints output containing the following:

> 2018/03/26 13:59:23 transport: http2Client.notifyError got notified that the client transport was broken EOF.
2018/03/26 13:59:23 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp 188.166.190.188:15021: getsockopt: connection refused"; Reconnecting to {188.166.190.188:15021 <nil>}
2018/03/26 13:59:24 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp 188.166.190.188:15021: getsockopt: connection refused"; Reconnecting to {188.166.190.188:15021 <nil>}

**Comment by 3Hren** [comment]
Yep, unfortunately it seems like there is no way to be notified about this except watching logs.
We'll provide more info about this in `sonmcli hub status` handler.

**Comment by D1abloRUS** [comment]
i get some error^

**Comment by 3Hren** [comment]
Hi! Your miner's ETH account must be allowed in the Hub's ACLs.
`sonmcli hub acl --help`

**Comment by 3Hren** [comment]
We've implemented the marketplace entirely in smart-contracts and have a CLI tool to determine whether it's up.
