### ISSUE TITLE
Feature: Allow user(s) to set device (CPU/GPU) usage cap/upper limit.

### ISSUE THREAD

**Issue by MeijeSibbel** [sonm-io/core#97]
Allowing a user to set a resource usage upper limit in percentage allows for example running the miner in the background. This also allows users to control the impact the miner has on system resources and tune it accordingly to the user's wishes.

**Comment by noxiouz** [comment]
https://github.com/sonm-io/core/pull/18 allows to a configure parent cgroup for all spawned containers. Right now we support memory/CPU limits. 
When it comes to GPU, it requires some extra investigation how to control it as AFAIK there's no general mechanism (like cgroups) to do it. However, having such mechanism sounds good.

**Comment by 3Hren** [comment]
CPU and memory limits can be tuned for an entire miner using cgroups (but in absolute values ATM). For GPUs there are no cgoups or other kind of limiting, so it is provided for a container in exclusive mode. If there are GPUs that are used for video rendering, we can automatically detect and exclude them from the list.

**Comment by MeijeSibbel** [comment]
Thanks for the quick reply guys, feel free to close the issue if you think its a duplicate. Very cool project you have going on here!.
