### ISSUE TITLE
Take into consideration user bandwidth limits

### ISSUE THREAD

**Issue by MeijeSibbel** [sonm-io/core#98]
From running the Alpha release it looks like there is a significant amount of network traffic that is generated by the miner. Some users have very limited bandwidth capabilities (e.g. 1Mbs/1Mbs), witch might cause issues like lag, timeouts...

**Comment by noxiouz** [comment]
Hi @MeijeSibbel! 
Traffic generated by miner and spawned containers can be throttled via cgroup/net_cls and tc-cgroup (outgress). I'll go for it. 
But it does not work for packets generated by remote hosts (ingress).

**Comment by 3Hren** [comment]
Also there are too frequent Docker status updates, which period has been restored from 5 to 30 seconds in #93 BTW as it was before.

**Comment by noxiouz** [comment]
Also, we can turn on data compression for gRPC

**Comment by 3Hren** [comment]
Closed in #107.
